#!/system/bin/sh

sleep 2

insmod /modules/lge_nv.ko
insmod /modules/lgosp_hid.ko
insmod /modules/fm_drv.ko
insmod /modules/ti_hci_drv.ko
insmod /modules/st_drv.ko

sleep 1

## Enable USB. WTF, JSON? Really??
echo '{ "personality" : 90510, "attached" : true, "configured" : true, "high-speed" : true }' > /sys/devices/platform/musb_hdrc/gadget/state
## Enable ADB & UMS
echo 1 > /sys/class/usb_composite/adb/enable
echo 1 > /sys/class/usb_composite/usb_mass_storage/enable

## THIS... IS... UGGLYYYYY!
killall -9 adbd
sleep 5
setprop service.adb.tmp.enable 1
