#!/system/bin/sh

if [ ! -r /data/misc/wifi/nvs_map.bin ]; then
	insmod /system/etc/wifi/tiwlan_drv.ko
	start wlan_loader
	cat << EOF | /system/bin/wlan_cu
/ w p 1 l 2 f 2 
/ t r h 0 7 
/ t b b 375 128 0 
/ t b t 1 0 0 0 0 0 0 0
/ q
EOF
	/system/bin/rmmod tiwlan_drv
	/system/bin/wifimac
fi
